# File: docker-stack.yml

version: '3.9'

services:
    db:
        image: viihnatech/shoutshack-db:latest
        deploy:
            restart_policy:
                condition: on-failure
        secrets:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        entrypoint: ['/usr/local/bin/entrypoint.sh']
        volumes:
            - db_data:/var/lib/postgresql/data
            - type: bind
              source: /home/viihna/viihnaFolders/cs-work/projects/shoutshack-v3/db/docker-entrypoint-initdb.d
              target: /docker-entrypoint-initdb.d
            - type: bind
              source: /home/viihna/viihnaFolders/cs-work/projects/shoutshack-v3/db/backups
              target: /var/lib/postgresql/backups
            - type: bind
              source: /home/viihna/viihnaFolders/cs-work/projects/shoutshack-v3/logs/db
              target: /var/log/postgresql
        ports:
            - '4553:5432'
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U $$(cat /run/secrets/POSTGRES_USER) -d $$(cat /run/secrets/POSTGRES_DB)'
                ]
            interval: 10s
            retries: 5
            start_period: 20s
            timeout: 5s

    server:
        image: viihnatech/shoutshack-server:latest
        deploy:
            restart_policy:
                condition: on-failure
        secrets:
            - POSTGRES_DB
            - POSTGRES_HOST
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        environment:
            NODE_ENV: development
        entrypoint: ['/usr/local/bin/entrypoint.sh']
        volumes:
            - type: bind
              source: /home/viihna/viihnaFolders/cs-work/projects/shoutshack-v3/logs/server
              target: /server/logs
        ports:
            - '3000:3000'
        depends_on:
            - db

    frontend:
        image: viihnatech/shoutshack-frontend:latest
        deploy:
            restart_policy:
                condition: on-failure
        ports:
            - '5173:5173'
        volumes:
            - type: bind
              source: /home/viihna/viihnaFolders/cs-work/projects/shoutshack-v3/logs/frontend
              target: /var/log/frontend

    nginx:
        image: viihnatech/shoutshack-nginx:latest
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
        volumes:
            - type: bind
              source: /home/viihna/viihnaFolders/cs-work/projects/shoutshack-v3/nginx/nginx.conf
              target: /etc/nginx/nginx.conf
              read_only: true
            - type: bind
              source: /home/viihna/viihnaFolders/cs-work/projects/shoutshack-v3/logs/nginx
              target: /var/log/nginx
            - type: bind
              source: /home/viihna/viihnaFolders/cs-work/projects/shoutshack-v3/.secrets
              target: /etc/nginx/secrets
              read_only: true
            - frontend_public:/usr/share/nginx/html
        ports:
            - target: 443
              published: 443
              mode: host
            - target: 80
              published: 80
              mode: host

volumes:
    db_data:
        external: true
    frontend_public:

secrets:
    POSTGRES_DB:
        external: true
    POSTGRES_HOST:
        external: true
    POSTGRES_USER:
        external: true
    POSTGRES_PASSWORD:
        external: true
