services:
  db:
    image: postgres:17.0
    restart: unless-stopped
    env_file:
      - .env
    user: "999:999"
    volumes:
      - db_data:/var/lib/postgresql/data
      - /home/viihna/Projects/shoutshack/db/tls:/var/lib/postgresql/tls:ro
      - /home/viihna/Projects/shoutshack/db/test/test-db.sql:/docker-entrypoint-initdb.d/test-db.sql
      - /home/viihna/Projects/shoutshack/db/init:/docker-entrypoint-initdb.d
      - /home/viihna/Projects/shoutshack/db/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - /home/viihna/Projects/shoutshack/db/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - /home/viihna/Projects/shoutshack/db/backups:/var/lib/postgresql/backups
    ports:
      - "5432:5432"
    networks:
      - shoutshack_network
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /home/viihna/Projects/shoutshack/backend/conf/.env:/app/conf/.env:ro
      - /home/viihna/Projects/shoutshack/backend/logs:/app/logs
    networks:
      - shoutshack_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    expose:
      - "3000"
    depends_on:
      - db
      - vault

  nginx:
    image: ./nginx
    restart: unless-stopped
    volumes:
      - /home/viihna/Projects/shoutshack/nginx/tls/nginx.crt:/etc/nginx/certs/nginx.crt:ro
      - /home/viihna/Projects/shoutshack/nginx/tls/nginx.key:/etc/nginx/certs/nginx.key:ro
      - /home/viihna/Projects/shoutshack/nginx/tls/rootCA.crt:/etc/nginx/certs/rootCA.crt:ro
      - /home/viihna/Projects/shoutshack/nginx/conf.d:/etc/nginx/conf.d:ro
      - /home/viihna/Projects/shoutshack/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/viihna/Projects/shoutshack/nginx/uploads:/usr/share/nginx/uploads
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443/udp"
      - "443:443"
    networks:
      - shoutshack_network
    depends_on:
      - backend
    command: ["nginx", "-g", "daemon off;"]

  vault:
    image: hashicorp/vault:1.14
    user: "0:0"
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=https://127.0.0.1:8200
      - VAULT_API_ADDR=https://127.0.0.1:8200
    ports:
      - "8200:8200"
    networks:
      - shoutshack_network
    volumes:
      - /home/viihna/Projects/shoutshack/vault/data:/vault/data
      - /home/viihna/Projects/shoutshack/vault/tls:/vault/tls:rw
      - /home/viihna/Projects/shoutshack/vault/config:/vault/config
      - /home/viihna/Projects/shoutshack/vault/entrypoint.sh:/vault/entrypoint.sh:ro
    command:
      ["/bin/sh", "-c", "/vault/entrypoint.sh && vault server -config=/vault/config/config.hcl"]

volumes:
  db_data:

networks:
  shoutshack_network:
    name: shoutshack_network
    driver: bridge
