# File: docker-compose.yml

services:
    server_backend:
        build: ./server/backend
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
        volumes:
            - ./server/backend:/app
            - /app/node_modules
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3000']
            interval: 10s
            retries: 5
            start_period: 10s

    frontend:
        build: ./frontend
        ports:
            - '5173:5173'
        volumes:
            - ./frontend:/app
            - /app/node_modules

    nginx:
        build: ./nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./.secrets:/etc/nginx/secrets:ro
        depends_on:
            server_backend:
                condition: service_healthy
