import setupLogger from './logger.js';
import { loadEnv } from '../utils/loadEnv.js';

loadEnv ({ logger: setupLogger() });

interface EnvironmentVariableTypes {
	BACKEND_LOG_EXPORT_PATH: string;
	EMAIL_USER: string;
	FEATURE_API_ROUTES_CSRF: boolean;
	FEATURE_DB_SYNC: boolean;
	FEATURE_DECRYPT_KEYS: boolean;
	FEATURE_ENABLE_CSRF: boolean;
	FEATURE_ENABLE_ERROR_HANDLER: boolean;
	FEATURE_ENABLE_IP_BLACKLIST: boolean;
	FEATURE_ENABLE_JWT_AUTH: boolean;
	FEATURE_ENABLE_RATE_LIMIT: boolean;
	FEATURE_ENABLE_REDIS: boolean;
	FEATURE_ENABLE_SESSION: boolean;
	FEATURE_ENABLE_SSL: boolean;
	FEATURE_HTTPS_REDIRECT: boolean;
	FEATURE_LOAD_TEST_ROUTES: boolean;
	FEATURE_SECURE_HEADERS: boolean;
	FEATURE_SEQUELIZE_LOGGING: boolean;
	FRONTEND_APP_JS_PATH: string;
	FRONTEND_BROWSER_CONFIG_XML_PATH: string;
	FRONTEND_CSS_PATH: string;
	FRONTEND_FONTS_PATH: string;
	FRONTEND_HUMANS_MD_PATH: string;
	FRONTEND_ICONS_PATH: string;
	FRONTEND_IMAGES_PATH: string;
	FRONTEND_JS_PATH: string;
	FRONTEND_KEYS_PATH: string;
	FRONTEND_LOGOS_PATH: string;
	FRONTEND_ROBOTS_TXT_PATH: string;
	FRONTEND_SECURITY_MD_PATH: string;
	FRONTEND_SECRETS_PATH: string;
	FRONTEND_SITEMAP_XML_PATH: string;
	LOGGER: string;
	NODE_ENV: 'development' | 'production';
	SERVER_DATA_FILE_PATH_1: string;
	SERVER_DATA_FILE_PATH_2: string;
	SERVER_DATA_FILE_PATH_3: string;
	SERVER_DATA_FILE_PATH_4: string;
	SERVER_LOG_PATH: string;
	SERVER_NPM_LOG_PATH: string;
	SERVER_PORT: string;
	SERVER_SSL_KEY_PATH: string;
	SERVER_SSL_CERT_PATH: string;
	STATIC_ROOT_PATH: string;
	YUBICO_API_URL: string;
}

export const environmentVariables: EnvironmentVariableTypes = {
	BACKEND_LOG_EXPORT_PATH: process.env.BACKEND_LOG_EXPORT_PATH || '',
	EMAIL_USER: process.env.EMAIL_USER || '',
	FEATURE_API_ROUTES_CSRF: process.env.FEATURE_API_ROUTES_CSRF === 'true',
	FEATURE_DB_SYNC: process.env.FEATURE_DB_SYNC === 'true',
	FEATURE_DECRYPT_KEYS: process.env.FEATURE_DECRYPT_KEYS === 'true',
	FEATURE_ENABLE_CSRF: process.env.FEATURE_ENABLE_CSRF === 'true',
	FEATURE_ENABLE_ERROR_HANDLER: process.env.FEATURE_ENABLE_ERROR_HANDLER === 'true',
	FEATURE_ENABLE_IP_BLACKLIST: process.env.FEATURE_ENABLE_IP_BLACKLIST === 'true',
	FEATURE_ENABLE_JWT_AUTH: process.env.FEATURE_ENABLE_JWT_AUTH === 'true',
	FEATURE_ENABLE_RATE_LIMIT: process.env.FEATURE_ENABLE_RATE_LIMIT === 'true',
	FEATURE_ENABLE_REDIS: process.env.FEATURE_ENABLE_REDIS === 'true',
	FEATURE_ENABLE_SESSION: process.env.FEATURE_ENABLE_SESSION === 'true',
	FEATURE_ENABLE_SSL: process.env.FEATURE_ENABLE_SSL === 'true',
	FEATURE_HTTPS_REDIRECT: process.env.FEATURE_HTTPS_REDIRECT === 'true',
	FEATURE_LOAD_TEST_ROUTES: process.env.FEATURE_LOAD_TEST_ROUTES === 'true',
	FEATURE_SECURE_HEADERS: process.env.FEATURE_SECURE_HEADERS === 'true',
	FEATURE_SEQUELIZE_LOGGING: process.env.FEATURE_SEQUELIZE_LOGGING === 'true',
	FRONTEND_APP_JS_PATH: process.env.FRONTEND_APP_JS_PATH || '',
	FRONTEND_BROWSER_CONFIG_XML_PATH: process.env.FRONTEND_BROWSER_CONFIG_XML_PATH || '',
	FRONTEND_CSS_PATH: process.env.FRONTEND_CSS_PATH || '',
	FRONTEND_FONTS_PATH: process.env.FRONTEND_FONTS_PATH || '',
	FRONTEND_HUMANS_MD_PATH: process.env.FRONTEND_HUMANS_MD_PATH || '',
	FRONTEND_ICONS_PATH: process.env.FRONTEND_ICONS_PATH || '',
	FRONTEND_IMAGES_PATH: process.env.FRONTEND_IMAGES_PATH || '',
	FRONTEND_JS_PATH: process.env.FRONTEND_JS_PATH || '',
	FRONTEND_KEYS_PATH: process.env.FRONTEND_KEYS_PATH || '',
	FRONTEND_LOGOS_PATH: process.env.FRONTEND_LOGOS_PATH || '',
	FRONTEND_ROBOTS_TXT_PATH: process.env.FRONTEND_ROBOTS_TXT_PATH || '',
	FRONTEND_SECURITY_MD_PATH: process.env.FRONTEND_SECURITY_MD_PATH || '',
	FRONTEND_SECRETS_PATH: process.env.FRONTEND_SECRETS_PATH || '',
	FRONTEND_SITEMAP_XML_PATH: process.env.FRONTEND_SITEMAP_XML_PATH || '',
	LOGGER: process.env.LOGGER || '',
	NODE_ENV: process.env.NODE_ENV as 'development' | 'production',
	SERVER_DATA_FILE_PATH_1: process.env.SERVER_DATA_FILE_PATH_1 || '',
	SERVER_DATA_FILE_PATH_2: process.env.SERVER_DATA_FILE_PATH_2 || '',
	SERVER_DATA_FILE_PATH_3: process.env.SERVER_DATA_FILE_PATH_3 || '',
	SERVER_DATA_FILE_PATH_4: process.env.SERVER_DATA_FILE_PATH_4 || '',
	SERVER_LOG_PATH: process.env.SERVER_LOG_PATH || '',
	SERVER_NPM_LOG_PATH: process.env.SERVER_NPM_LOG_PATH || '',
	SERVER_PORT: process.env.SERVER_PORT || '',
	SERVER_SSL_KEY_PATH: process.env.SERVER_SSL_KEY_PATH || '',
	SERVER_SSL_CERT_PATH: process.env.SERVER_SSL_CERT_PATH || '',
	STATIC_ROOT_PATH: process.env.STATIC_ROOT_PATH || '',
	YUBICO_API_URL: process.env.YUBICO_API_URL || ''
};
